rapidez/statamic

src/Http/StatamicDataComposer.php, src/RapidezStatamicServiceProvider.php
Alternative version that uses a singleton, reducing the amount of Cache calls from many (very many) per request to just one
=> Globals everywhere via singleton

src/Http/Controllers/StatamicRewriteController.php
[Because statamic demands it](https://statamic.dev/repositories/entry-repository#querying)
=> Changed "locale" to "site"

resources/js/components/FormConditions.vue, resources/js/package.js, resources/views/form_fields/select.blade.php, resources/views/form_fields/text.blade.php, resources/views/form_fields/textarea.blade.php, resources/views/page_builder/form.blade.php, src/Forms/JsDrivers/Vue.php, src/Forms/Vue.php, src/RapidezStatamicServiceProvider.php
Also adds a simple `select` field
=> Add conditionals to form via JS Driver

composer.json, resources/views/breadcrumbs.blade.php
https://github.com/rapidez/core/pull/289
should be merged and released first
=> Use url helpers

README.md, config/rapidez-statamic.php, resources/views/utilities/import_utility/imports.blade.php, src/Actions/StatamicEntryAction.php, src/Commands/ImportCategories.php, src/Commands/ImportProducts.php, src/Http/Controllers/ImportsController.php, src/RapidezStatamicServiceProvider.php
This PR adds the product import command.
This also adds a utility to run the import commands from the Statamic CP.
=> Add product import command & add utility to start imports

README.md, config/rapidez-statamic.php, resources/blueprints/collections/brands/brand.yaml, resources/content/collections/brands.yaml, resources/views/utilities/import_utility/imports.blade.php, src/Commands/ImportBrands.php, src/Http/Controllers/ImportsController.php, src/RapidezStatamicServiceProvider.php
This commit adds a basic collection for brands, and adds a command to import brands into the collection.
=> Import brands command

README.md, composer.json, resources/views/page_builder/content.blade.php, src/Http/ViewComposers/StatamicGlobalDataComposer.php, src/RapidezStatamicServiceProvider.php
BREAKING
Since optionalDeep will always return the optional class we explicitly need to ask it if a value is set
```diff
- @if($globals->cookie_notice->text)
+ @if($globals->cookie_notice->text->isset())
```
This also means that checks for specific values need to be updated
```diff
- @if($globals->cookie_notice->text === 'foo')
+ @if($globals->cookie_notice->text->get() === 'foo')
```
=> Implement optionalDeep add migration notice

resources/views/brands/show.blade.php
- Added container around content, breadcrumbs and pagebuilder.
- Added some margin for top & bottom of page and between listing & content.
=> Added container classes on places where needed

src/Commands/InvalidateCacheCommand.php, src/RapidezStatamicServiceProvider.php
=> [4.x] Static caching with invalidation on Magento urls

src/RapidezStatamic.php
=> [5.x] Change cache key for nav tree

resources/js/package.js
5.x version of #103 , for explaination see #103
=> [5.x] Reload csrf token when statamic reloads it

src/RapidezStatamicServiceProvider.php
see: https://github.com/rapidez/statamic/pull/107
=> [4.x] Fixed infinite locking for certain requests

src/RapidezStatamicServiceProvider.php
4.x version of https://github.com/rapidez/statamic/pull/109
=> [4.x] StartPush on view composer

src/RapidezStatamicServiceProvider.php
My mistake, in my local copy of the repository this is still somehow in there.
=> [4.x] Add controller into includes

src/Commands/InvalidateCacheCommand.php
This fixes the LatestCheck from being deleted by clearing the cache.
Instead of selecting an alternative caching method i've opted with using the same methods as statamic uses for static caching.
This has the following advantages:
We cannot accidentally select a cache driver that will also be cleared
The latest execution is visible plaintext when logging into the server
The latestCheck value will only be removed when clearing the entire static cache (using the backend or the statamic comment)
4.x: https://github.com/rapidez/statamic/pull/124
=> Save latestCheck with static files

src/Commands/InvalidateCacheCommand.php
Changing the stock does not actually update the updated_at value of the product. (because Magento performs some queries directly into the database)
See: #129
=> [5.x] Invalidate product pages on stock changes

resources/js/components/FormConditions.vue
See: https://github.com/rapidez/statamic/pull/131
=>  Replace CSRF token in the Vue form

composer.json, src/RapidezStatamicServiceProvider.php
See: https://github.com/rapidez/statamic/pull/140
=> [4.x] Redirect absolute domains ending in . to regular domain

src/Observers/RunwayObserver.php
This was removed and replaced with this specific if statement within Runway v8.5.0.
=> [5.x] Remove Json helper

src/Extend/SitesLinkedToMagentoStores.php
by default cache also requires the database
=> Move try/catch around cache

resources/views/page_builder/form.blade.php
Make use the secondary button here instead of the `<x-rapidez::button>` because this button doesn't have a very nice color.
=> Make use of secondary button

composer.json, resources/views/brands/show.blade.php
=> Rapidez v4 Compatibility
