- README.md
- src/Commands/ImportCategories.php
- src/RapidezStatamicServiceProvider.php
Multiple examples of usages are
```bash
php artisan rapidez:statamic:import:categories --all
php artisan rapidez:statamic:import:categories --all --site=default
php artisan rapidez:statamic:import:categories 5 8 9 category-url-key --site=default --site=another_site
```
If you have a custom blueprint and would like to add more data from the category you can do so by hooking into the `rapidez-statamic:category-entry-data` event 
```php
Event::listen('rapidez-statamic:category-entry-data', fn($category) => [
'description' => $category->description,
]
);
```
> Add command to import magento categories into statamic entities

- src/Models/Brand.php
Runway crafts queries that don't take into account the possibility of having a query like this. For example, it assumes that the primary key is unique and doesn't need to be qualified.
By adding these subqueries we can rename the ambiguous keys before they become a problem.
> Remove ambiguous keys from query to help runway figure itself out

- src/Models/Brand.php
- src/Models/Category.php
- src/Models/Product.php
The problem with using the selected() method is that it looks at your session to get the selected site in from CP like so:
`return $this->get(session('statamic.cp.selected-site')) ?? $this->default();`
This is why it would default to look in the default site on the frontend. Using the current() method fixes this as this is the method intended for the frontend.
> Retrieve data from the actual current site

- resources/views/form_fields/select.blade.php
x-select is not a blade component, thus view caching fails and cannot finish if this package is installed.
This resolves it
> Fix view caching by loading correctly scoped select input

- composer.json
- resources/views/page_builder/form.blade.php
Laravel includes only accept array as parameters for the view files.
Depending on nesting $set is an optionalDeep instance or an array already.
This way we are safe for both cases.
> Guarantee includeFirstSafe recieves array

- src/Http/ViewComposers/StatamicGlobalDataComposer.php
When this is set in the __constructor, composer install will try to run this code in the autoload when it does `package:discover`. This can cause issues when the sql server isn't set up, for example.
> Move globals to getGlobals function instead of constructor

- src/Models/Brand.php
- src/Models/Category.php
- src/Models/Product.php
When switching sites in the backend this didn't change the products listed in runway. This fixes that and keeps current functionality working
> Use the selected site in the control panel

- src/RapidezStatamicServiceProvider.php
Sometimes the globals do get forgotten from the cache, but the views are still cached, hence you don't see the changes to globals.
> Also clear view cache

- src/Http/ViewComposers/StatamicGlobalDataComposer.php
This improves performance significantly, without this for every view we hit the cache driver.
> Cache the globals in memory

- composer.json
- config/rapidez/statamic/builder.php
- src/Collections/Categories.php
- src/Collections/Products.php
- src/Models/Category.php
- src/Models/Product.php
- src/Models/Traits/HasContentEntry.php
- src/Observers/RunwayObserver.php
- src/RapidezStatamicServiceProvider.php
This extends the functionality in #80 . It adds a trait for the linking of a content entry, also added the collections via Statamic builder. The trait uses 2 variables in the model to determine which collection is used and which field on it is used to link the content on. 
```php
public string $linkField = 'linked_category';
public string $collection = 'categories';
```
I also moved the model events to a observer so we can use it for multiple model types.
```php
#[ObservedBy([RunwayObserver::class])]
class Category extends Model
{
```
The only downside of using the Statamic builder package is it forces to use all the functions and we don't need them.
We still need to figure out a way to not display the "Content" collections in the CP.  I think we can manage it at …
> Hybrid Runway extended

- composer.json
- src/Extend/SitesLinkedToMagentoStores.php
- src/Http/ViewComposers/StatamicGlobalDataComposer.php
- src/Models/Category.php
- src/Models/Product.php
This implements an array cache to some often used functions.
Quick breakdown:
`FindByUrl` and by extension `findByMageRunCode` is getting hit `313` times.
On single store (or simply without the MAGE_RUN_CODE) this would result in 626 creations and lookups in a collection.
if the code is missing the `findByMageRunCode` cache is never created, thus the falsey check saves us on 313 lookups in case that header is missing. Otherwise we can assume the site will be found.
the casting of the large array of globals to object, and passing it to optionalDeep seems relatively heavy.
and it is executed `284` times (per view it is executed)
We cannot store it in Redis cache without breaking the object, thus array store is the best option here.
> Implement performance optimizations

- src/Commands/InvalidateCacheCommand.php
- src/RapidezStatamicServiceProvider.php
It just adds the static caching middleware on the `web` middleware group, this way all urls can be cached. To invalidate changed pages the `rapidez-statamic:invalidate-cache` should be scheduled, all info will go into the docs later.
There are some todo's left:
- Docs
- Double check with multisites
- Optionally; cache warming
Ah and.. we could cherry pick this into 4.x if we want this in Rapidez v2 installations.
> Static caching with invalidation on Magento urls

- src/RapidezStatamicServiceProvider.php
In some cases there is a problem in the way the `magento_store_id` attribute in the sites.yaml is being parsed through antlers.
When getting the attribute from the site the store ID is not always being cast as an integer but as a string.
I've made some changes to cast this as an integer.
> Get site by Store ID fix

- src/Jobs/GenerateStoreSitemapJob.php
Had to prefix the url with `storage/` as the Statamic sitemaps weren't available on `/rapidez-sitemaps/1/statamic_sitemap_collection_pages.xml` but actually on `/storage/rapidez-sitemaps/1/statamic_sitemap_collection_pages.xml`.
> Fixed public url for statamic sitemaps

- src/RapidezStatamic.php
This cache key clashed with the one used for `navCache` below. This caused it to sometimes (but not always) throw a 500 error after a cache clear.
> [4.x] Change cache key for nav tree

- src/Extend/SitesLinkedToMagentoStores.php
If we're automaticly setting the statamic sites we can also set the static caching paths. This way we don't need the urls in the `.env` when using static caching.
> [5.x] Automaticly set the config of the static caching paths when enabled

- resources/js/package.js
Whenever Static caching is used, Statamic updates the CSRF token however our vue propery is not yet updated. This add's the functionality that the vue property get's refreshed also.
> [4.x] Reload csrf token when statamic reloads it

- src/RapidezStatamic.php
Some projects we have use an empty link item to have a heading above other links. When this is used the `url_path` on the linked runway resource is not present. This adds a early return for that.
5.x: #106
> [4.x] Return if url path is not set on the linked entry

- src/RapidezStatamic.php
Some projects we have use an empty link item to have a heading above other links. When this is used the `url_path` on the linked runway resource is not present. This adds a early return for that.
4.x: #105
> [5.x] Return if url path is not set on the linked entry

- src/RapidezStatamicServiceProvider.php
Because of the locking implemented in https://github.com/statamic/cms/blob/8a2ad86a7b7ad8a76c37db3ee3ff71ecbad45627/src/StaticCaching/Middleware/Cache.php#L59
running this middleware twice will force it to lock forever:
1. First time calling the function in: create the lock until i get my response, call the next middleware in the chain
2. Second time calling the middleware: There is a lock active for this request, i must wait for that to release before proceeding to the next middleware.
This will cause an infinite wait time.
As the web middleware group will always be applied we can remove the middleware from the statamic.web middleware group
> Fixed infinite locking for certain requests

- src/RapidezStatamicServiceProvider.php
Alternative of: https://github.com/rapidez/core/pull/701
The issue arises when we get an error while attempting to render a page, e.g. a 404. Here's a play by play of what happens:
1. A user navigates to a nonexistent page that will throw a 404
2. The app boots
3. The pipelines and controllers all happen, eventually arriving at Statamic's frontendcontroller which tries to find a page
4. Statamic renders a view, fails, and throws a 404
5. The Laravel Pipeline catches this error and goes on to render a 404 page. Critically, this doesn't re-boot the app because it has already booted.
Note that both step 4 and step 5 render a view, and also note that when a view gets rendered, it will flush the stacks. Ultimately, this means that when you get a 404 page, this startPush has been consumed by …
> Do startPush on view composer instead of boot

- composer.json
- src/Commands/InstallCommand.php
- src/Models/BaseUser.php
- src/Models/User.php
- src/RapidezStatamicServiceProvider.php
Changed the flow for the install command a bit, also added the configuration for the User model so we don't need https://github.com/rapidez/statamic/pull/90 anymore.
The flow of the install command now is as follows:
- We're starting with setting up Statamic by running the statamic:install command followed up by adding `@php artisan statamic:install --ansi` into the post-autoload-dump, as Statamic's install command doesn't do that.
Next we setup everything for the user by: 
- Setting the User model from the rapidez/statamic package in the auth config.
- Checking if the user migration exists, if not we get it from the Laravel repository.
- We change some config files and to comply with what's needed according to https://statamic.dev/tips/storing-users-in-a-database#in-an-existing-laravel-ap …
> Refactored install command

- src/Commands/InstallCommand.php
With this PR we change the install command to extend the base user model from the package instead of forcing to use the one from the package.
> Extend user model if it already exists

- composer.json
- config/rapidez/statamic.php
- src/Models/Traits/HasContentEntry.php
- src/Observers/RunwayObserver.php
I've tested this with all the types (Brands, Categories and Products). This will add the right attributes to the model and render them in the entry in the backend of Statamic. This won't change anything for the frontend. It's still adding the content to the views as expected.
I also updated Runway. There's been some fixes for relation fields between Runway models. If you have a relations field on a Runway model called "products" it expected to have a "products" relation on the runway model. This is fixed now.
The upgrade guide show's no high impacting changes that applicable for us: https://runway.duncanmcclean.com/upgrade-guides/v7-to-v8
> [5.x] Use the retrieved event instead of having to overwrite getAttributes

- composer.json
- src/RapidezStatamicServiceProvider.php
- src/StaticCaching/CustomInvalidator.php
5.x version of https://github.com/rapidez/statamic/pull/122
---
Added a basic cache invalidator for emptying the caches when the relevant content has changed.
This new class can also be extended and used as a base in projects where more custom validation rules are required.
> [5.x] Added custom cache invalidator

- src/Commands/InstallCommand.php
As `yarn run prod` will fail when it's running from `php artisan rapidez:install` and selecting Magento with:
> [vite]: Rollup failed to resolve import "/public/vendor/statamic/frontend/js/helpers.js" from "/Users/roy/code/rapidez2/vendor/rapidez/statamic/resources/js/components/FormConditions.vue".
But after this command `php artisan rapidez-statamic:install` it's working so just build at the end.
> Compile assets from the install command

- src/Commands/InvalidateCacheCommand.php
Changing the stock does not actually update the updated_at value of the product. (because Magento performs some queries directly into the database)
> [4.x] Invalidate product pages on stock changes

- resources/js/components/FormConditions.vue
Sometimes the token is already replaced by Statamic, when Vue loads slower the token resets back to `STATAMIC_CSRF_TOKEN`. With this we're replacing on form load.
> Replace CSRF token in the Vue form

- src/Commands/InvalidateCacheCommand.php
This PR adds store code to static cache path when we have multiple paths defined, even though there might only be one store, the developer still could've set these config values as an array.
Tested on 4.x and 5.x, with multistore and single store.
5.x: #133
> [4.x] InvalidateCacheCommand multistore compatible

- src/Commands/InvalidateCacheCommand.php
This PR adds store code to static cache path when we have multiple paths defined, even though there might only be one store, the developer still could've set these config values as an array.
Tested on 4.x and 5.x, with multistore and single store.
4.x: #134
> [5.x] InvalidateCacheCommand multistore compatible

- composer.json
- src/RapidezStatamicServiceProvider.php
See: https://github.com/statamic/cms/pull/11782
Domains ending in . is breaking for sites implementing static caching. This change will automatically redirect those domains to the version not ending in .
(also removed some imports that were unused)
> Redirect absolute domains ending in . to regular domain

- src/Extend/SitesLinkedToMagentoStores.php
- src/RapidezStatamicServiceProvider.php
This caused pipelines that don't instantiate a database to fail because it tried to run a db query.
> [5.x] Fix db query running on composer install

- src/RapidezStatamicServiceProvider.php
When getting the entry directly like here, Statamic doesn't find the right blueprint because it only looks in the `collections/[handle]` folder. This is hardcoded within Statamic so there's no easy way around that. This means that all category pages and product pages in the frontend (not the backend) currently break due to there being no blueprint attached to them, giving you raw data instead of augmented data.
However, we can trick statamic into looking elsewhere by setting a custom namespace like this. It's a pretty gross hack, I don't like it. But it's the only thing I found that works.
We have to make sure it doesn't run when in the backend because otherwise it will show the extra blueprints from these hacky namespaces.
> [5.x] Hack in namespace so statamic gets the correct blueprint

- src/Observers/RunwayObserver.php
When you create for example a `meta_title` and `meta_description` field in the Runway category blueprint it will conflict with the Magento values. Before this the Statamic value will be used but when you revisit the category you'll see the Magento value. We could just merge it differently but when you clear the value it should actually be empty instead of having the Magento value saved in Statamic. With this approach we remove potential duplicated/conflicting values.
> Merge conflicting fields correctly

- src/Observers/RunwayObserver.php
The `entity_id` and `name` are correct for products (although missing SKU) and categories, but not for the brands. As we've already made all the relevant fields read_only in the blueprint, we can just listen to that instead.
> [6.x] Improve filtering of attributes on retrieved models

- src/Models/Traits/HasContentEntry.php
- src/Observers/RunwayObserver.php
This is useful for when you don't want to change your primary key, which could have various reasons.
> [6.x] Allow for arbitrary link keys instead of just the primary key
